version: "3.9"

services:
  backend:
    build: ./backend/
    ports:
      - "8000:8000"
    command: dev
    volumes:
      - ./backend/domomir_backend:/app
    environment:
      - GUNICORN_CONFIG=/srv/gunicorn/config.dev.py
  frontend:
    build:
      context: ${PWD}/frontend/
      dockerfile: ${PWD}/frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
