version: "3.9"

services:
  backend:
    build: ${PWD}/backend/
    environment:
      - YAMLCONF_CONFFILE=/srv/config.yaml
    volumes:
      - ${PWD}/etc/database/:/srv/database/
      - ${PWD}/etc/upload/:/srv/upload/
      - ${PWD}/etc/app_config/config.yaml:/srv/config.yaml
      - ${PWD}/etc/nginx/nginx_backend.conf:/etc/nginx/nginx.conf
    user: app
    expose: ["8000"]

  frontend:
    build:
      context: ${PWD}/frontend/
      dockerfile: ${PWD}/frontend/prod.Dockerfile
    volumes:
      - ${PWD}/etc/nginx/nginx_frontend.conf:/etc/nginx/nginx.conf
    user: app 
    expose: ["8500"]

  celery-worker:
    build: ${PWD}/backend/
    environment:
      - YAMLCONF_CONFFILE=/srv/config.yaml
    volumes:
      - ${PWD}/etc/database/:/srv/database/
      - ${PWD}/etc/app_config/config.yaml:/srv/config.yaml
    command: celery-worker 

  celery-beat:
    build: ${PWD}/backend/
    environment:
      - YAMLCONF_CONFFILE=/srv/config.yaml
    volumes:
      - ${PWD}/etc/database/:/srv/database/
      - ${PWD}/etc/app_config/config.yaml:/srv/config.yaml
    command: celery-beat

  redis:
    image: redis:latest
    expose: ["6379"]
