version: "3.9"

services:
  backend:
    build: ./backend/
    image: domomir_backend
    environment:
      - DJANGO_SECRET=secret
    volumes:
      - domomir-etc:/srv/etc/
    expose: ["8000"]

  frontend:
    build: 
      context: ./frontend/
      dockerfile: ./prod.Dockerfile
    image: domomir_frontend
    expose: ["8500"]

  celery-worker:
    build: ./backend/
    image: domomir_backend
    volumes:
      - domomir-etc:/srv/etc/
    command: celery-worker 

  celery-beat:
    build: ./backend/
    image: domomir_backend
    volumes:
      - domomir-etc:/srv/etc/
    command: celery-beat

  redis:
    image: redis:latest
    expose: ["6379"]

  nginx:
    image: nginx:alpine
    volumes:
      - ./etc/nginx/nginx_proxy.conf:/etc/nginx/nginx.conf:ro
      - ./etc/nginx/proxy_params:/etc/nginx/proxy_params
    ports:
      - "8080:80"

volumes:
  domomir-etc:
    external: true
