# Generated by Django 4.0.1 on 2022-09-05 17:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitness', '0002_rename_sets_trainingexercise_set_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trainingplan',
            unique_together={('weekday', 'owner', 'training')},
        ),
    ]
