# Generated by Django 4.0.1 on 2022-09-05 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_alter_trainingplan_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingexercise',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='fitness.training'),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='training',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_plan', to='fitness.training'),
        ),
    ]
