DEBUG: false
SHUTTER_IP_ADDRESS: '192.168.50.201'
SHUTTER_PROXY_ADDRESS: 'http://192.168.50.150:8555/'
STATIC_ROOT: '/srv/etc/static'
MEDIA_ROOT: '/srv/etc/upload'
DATABASES:
  default:
    ENGINE: 'django.db.backends.sqlite3'
    NAME: '/srv/etc/database/db.sqlite3'
