# Generated by Django 4.0.1 on 2022-01-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tag_type', models.CharField(choices=[('primary', 'Blue'), ('secondary', 'Grey'), ('success', 'Green'), ('danger', 'Red'), ('warning', 'Orange'), ('info', 'Light Blue'), ('light', 'Light Grey'), ('dark', 'Black')], default='primary', max_length=24)),
            ],
        ),
    ]
