# Generated by Django 4.0.1 on 2022-01-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_remove_recipe_thumbnail_alter_recipe_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='foods.RecipeTag'),
        ),
    ]
