# Generated by Django 4.0.1 on 2022-08-21 10:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_recipe_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryPicture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='temp_pictures/')),
            ],
        ),
    ]
