# Generated by Django 4.0.1 on 2022-08-21 15:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_temporarypicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipePicture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='temp_pictures/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_picture', to='foods.recipe')),
            ],
        ),
        migrations.DeleteModel(
            name='TemporaryPicture',
        ),
    ]
