# Generated by Django 4.0.1 on 2022-08-21 15:43

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_recipepicture_delete_temporarypicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='picture',
        ),
        migrations.AlterField(
            model_name='recipepicture',
            name='file',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='recipe_pictures/'),
        ),
    ]
