# Generated by Django 4.0.1 on 2022-08-21 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0008_remove_recipe_picture_alter_recipepicture_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipepicture',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='picture',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='foods.recipepicture'),
        ),
    ]
