# Generated by Django 4.0.1 on 2022-08-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0009_remove_recipepicture_recipe_recipe_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipetag',
            name='tag_type',
        ),
        migrations.AlterField(
            model_name='recipetag',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
