# Generated by Django 4.0.1 on 2022-08-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0011_remove_recipe_ingredients_recipeingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount_and_unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
