# Generated by Django 4.0.1 on 2022-08-31 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0012_alter_recipeingredient_amount_and_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepicture',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
