# Generated by Django 4.0.1 on 2022-08-31 20:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0013_alter_recipepicture_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepicture',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
