# Generated by Django 4.0.1 on 2022-09-03 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0016_shoppinglistitem_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinglistitem',
            options={'ordering': ('marked_as_done', '-created')},
        ),
    ]
