# Generated by Django 4.0.1 on 2024-02-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0017_alter_shoppinglistitem_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='author',
        ),
    ]
